### ISSUE TITLE
test_actor_with_mocked_method_works

### ISSUE THREAD

**Issue by linpan** [jodal/pykka#100]
```
>       assert mock.call_count == 1
E       assert 0 == 1
```
will better if write this:
    assert proxy.a_method().get() == "mocked method return" # this will call mock a_method.
    assert mock.call_count == 1

**Comment by jodal** [comment]
Is this from the Pykka test suite or from documentation examples?

**Comment by linpan** [comment]
from  Pykka test suite path:/tests/proxy/test_mocking::test_mocking.py

**Comment by jodal** [comment]
I'm sorry, I still don't understand what should be changed here and why. I'm closing the issue as I don't expect a reply after I've been silent for four months myself.
