### ISSUE TITLE
Please package testsuite to the distribution tarball on PyPI

### ISSUE THREAD

**Issue by mcepl** [jodal/pykka#171]
I would like to fix packaging for OpenSUSE, but your [release tarball](https://files.pythonhosted.org/packages/fd/9c/ba729a18d0430f18931a454563606441626b0162752d9cbfa3f66068f53b/pykka-3.0.2.tar.gz) does not contain the tests directory. Could you please distribute them as well?

**Comment by jodal** [comment]
As a Debian Developer, I appreciate where you're coming from and why you want this. Pykka used to ship the test suite. I guess this might have been lost in the move from setuptools to Poetry in Pykka 3.0, but it has not intentionally been removed. I'll see what I can do about it :-)

**Comment by jodal** [comment]
3.1.0 is on PyPI now. It should include the test suite.
