### ISSUE TITLE
Installs setup.cfg and tox.ini

### ISSUE THREAD

**Issue by mcepl** [jodal/pykka#172]
When running packaging 3.1.0 (with some additional parameters for weird world of Linux distribution packaging):
```sh
python3 -mpip wheel
python3 -mpip install *.whl
```
I got `setup.cfg` and `tox.ini` installed in `/usr/lib/python3.*/site-packages` directory. Something's wrong.

[Complete build log](https://github.com/jodal/pykka/files/8789591/_log.txt)

**Comment by jodal** [comment]
The `setup.py` that Poetry generates for backwards compat seems to install any included files (not directories) into `site-packages`. Pykka 3.1.1 is being built right now. It no longer includes those files in the source tarball.

**Comment by mcepl** [comment]
Does `poetry` still uses `MANIFEST.in`?

**Comment by jodal** [comment]
No, it doesn't. It handles typical cases like `py.typed` itself, and you can specify extra includes/excludes in `pyproject.toml`, like here: https://github.com/jodal/pykka/blob/main/pyproject.toml#L17
