### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by girst** [jodal/pykka#200]
Pykka (and therefore Mopidy) currently fail to build from source on Fedora Rawhide (soon to be 39). In the mean time I've submitted a patch to Fedora to fix up the version we currently ship, but I intend to become co-maintainer and get pykka up to date, too.

The following commit is needed to get it to build with Sphinx 6.1.3: https://github.com/jodal/pykka/commit/675026b86f818da6deb25049c650c21723165420#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3    
Fedora Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2180466

**Comment by jodal** [comment]
I assume it is only the change in `docs/conf.py` you need right now, to fix the Fedora build?

I plan to release a 4.0 soon with the typing changes already merged into `main`, but I want to try the typing improvements with Mopidy before releasing it. Due to vacations, I can't promise that will happen until later this summer.

**Comment by girst** [comment]
On Fri, Jul 14, 2023 at 03:51:36PM -0700, Stein Magnus Jodal wrote:
>I assume it is only the change in `docs/conf.py` you need right now, to 
>fix the Fedora build?

yes, that is enough to get it to build again.

>I plan to release a 4.0 soon with the typing changes already merged 
>into `main`, but I want to try the typing improvements with Mopidy 
>before releasing it. Due to vacations, I can't promise that will happen 
>until later this summer.

in that case i can wait. as mentioned, i have patches to support our 
(admittedly aging) pykka package ready, so it's not time critical :)

**Comment by jodal** [comment]
Pykka 4.0.0 has been released now: https://github.com/jodal/pykka/releases/tag/v4.0.0
