### ISSUE TITLE
Problem with multiprocessing in derived class of pykka.ThreadingActor

### ISSUE THREAD

**Issue by HB-GSI** [jodal/pykka#204]
Hello
I've got a problem to start processes using python's multiprocessing package with an derived actor class of pykka.ThreadingActor and have no explanation. 

- Starting processes from __main__ works fine.
- Starting processes from with the derived actor class does not to work (at least not as expected).

Most parts of my application is IO bound, but one specific task is CPU bound. I tries to perform the CPU bound calculations in extra processes started from within the derived actor class to make use of all available CPU cores.

The attached example illustrates the behavior. The script asks the user which model to use pure multiprocessing or multiprocessing within pykka actor class and which task to start, a simple or complex, with one task or two tasks communicating using multiprocessing.Queue(). All tasks write some output to file to the working directory to verify their activity.

What' wrong with my script?

Best Holger

[mp_actor.zip](https://github.com/jodal/pykka/files/12269903/mp_actor.zip)

**Comment by HB-GSI** [comment]
On Windows the script generates an exception. 
Please replace 'task_test' with process_task_test' to avoid shadowing.
Best Holger

**Comment by HB-GSI** [comment]
OK, problem found. It's a bit embarrassing.
It's an artifact form the creation of the sample as copy of the original class which is already a derived class using the channel pattern calling _on_start() of derived classes etc.

Renaming the '_on_start()' etc to 'on_start()' etc. solved the problem an the processes are started as expected.

Best Holger
[mp_actor.zip](https://github.com/jodal/pykka/files/12274810/mp_actor.zip)

**Comment by jodal** [comment]
Thanks for taking the time to explain what your solution was!
