### ISSUE TITLE
Pykka test support

### ISSUE THREAD

**Issue by fatuhoku** [jodal/pykka#25]
One of the main advantages of using the Actor model is its ease of testing.

Every actor is by default isolated and so verifying the individual behaviours of Actors should be easy because we can provide each actor with fake / stub collaborators and verify that the right messages (of the appropriate formats) are sent and received.

However, it's not simple to capture this in the form of an assertion in a unit test.

Perhaps a couple of examples of how Pykka actors can be tested with popular test/mocking frameworks would help here.

**Comment by jodal** [comment]
I've created a testing section in the docs, initially with the tips from this issue and some pytest examples: https://www.pykka.org/en/develop/testing/
