### ISSUE TITLE
How comes I can't see Pykka debug log messages?

### ISSUE THREAD

**Issue by fatuhoku** [jodal/pykka#31]
EDIT: I've solved my problem. I thought the `pykka` logger was somehow buggered but in actual fact, file configuration caused the issue. See the [last comment on this issue](https://github.com/jodal/pykka/issues/31#issuecomment-24843873).

I feel the solution could be documented in Pykka, mainly because it was non-trivial for me to find out that:
- how logging was supposed to work when a library obtains their own logger, e.g. `pykka`
- whether logging causes problems when working with multiple threads (it doesn't)
- whether `logging.getLogger('pykka')` gets the exact instance of the logger as Pykka does (it does)
- how then to set the logger's level to DEBUG; how the root logger's level also needs to be set to DEBUG for messages to show.

**Comment by adamcik** [comment]
I was just chatting with @jodal earlier today about how there is currently no way to determine of `on_start` succeed. When double checking the open issues before filling a new one I came across this which is essentially what I brought up in the context of Mopidy startup.

Given the current API a somewhat reasonable workaround in our case is just to "ping" the actor, that is to call some harmless method and see if it works. My initial attempt just used `is_alive`, but this could easily win a race against slow `on_start` code.

As for fixing this, the conclusion was simply to document this for now. And then for an eventual new major release better API support for startup might be worth looking into.

**Comment by jodal** [comment]
The develop version of the docs now have a better section on logging with Pykka and recommended setups: https://www.pykka.org/en/develop/api/logging/
