### ISSUE TITLE
Can not import GeventActor

### ISSUE THREAD

**Issue by wylyeak** [jodal/pykka#58]
version detail:
* gevent==1.0.2
* Pykka==1.2.1
* Mac Yosemite 10.10.4

pykka.GeventActor

> Traceback (most recent call last):
>      File "<stdin>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'GeventActor'

how can i import GeventActor?

**Comment by jodal** [comment]
Since the gevent support requires gevent, it is in a submodule named `pykka.gevent` so that `pykka` is usable without `gevent` installed.

This should work for you:

``` python
from pykka.gevent import GeventActor
```
