### ISSUE TITLE
Maximum

### ISSUE THREAD

**Issue by dastultz** [jodal/pykka#62]
Hello, I love the "proxy" feature of Pykka! But I often run in to this pattern that yields `RuntimeError: maximum recursion depth exceeded while calling a Python object`. I can't pass a proxy in to the constructor of another actor.

```python
import pykka

class MySupervisor(pykka.ThreadingActor):
    
    def __init__(self):
        super(MySupervisor, self).__init__()
        self.use_daemon_thread = True
        self.in_future = self.actor_ref.proxy()
        self.worker = Worker.start(self.in_future).proxy()

class Worker(pykka.ThreadingActor):
    
    def __init__(self, supervisor):
        super(Worker, self).__init__()
        self.use_daemon_thread = True

sup = MySupervisor.start().proxy()
```

**Comment by jodal** [comment]
On the last line, you create a proxy to `MySupervisor`. When creating a proxy, the attributes of the actor is inspected to see what attributes should be made available through the proxy. It also looks for the `pykka_traversible` attribute on each attribute, to see if it should recurse into that object.

Basically what happens is that there is an infinite loop inspecting `in_future`. By making the `in_future` attribute private, the example works:

``` python
import logging

import pykka

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

class MySupervisor(pykka.ThreadingActor):

    def __init__(self):
        super(MySupervisor, self).__init__()
        self.use_daemon_thread = True
        self._in_future = self.actor_ref.proxy()
        self.worker = Worker.start(self._in_future).proxy()

class Worker(pykka.ThreadingActor):

    def __init__(self, supervisor):
        super(Worker, self).__init__()
        self.use_daemon_thread = True

sup = MySupervisor.start().proxy()

logger.info('Started')
```

**Comment by dastultz** [comment]
Ahh, fantastic. That solved my problem. Thanks for the quick reply.
